# Generated by Django 4.1.5 on 2023-01-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_project_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project_photos',
            new_name='project_photo',
        ),
    ]
