# Generated by Django 4.1.5 on 2023-01-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_project_photos_project_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
