# Generated by Django 4.1.5 on 2023-01-28 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_project_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_photo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pages.project'),
        ),
    ]
