# Generated by Django 4.2.2 on 2025-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_projectphoto_project_architect_project_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='accordion_architecture_image',
            field=models.ImageField(blank=True, null=True, upload_to='main/', verbose_name='Architecture Design Resim'),
        ),
        migrations.AlterField(
            model_name='main',
            name='accordion_engineering_image',
            field=models.ImageField(blank=True, null=True, upload_to='main/', verbose_name='Engineering Plan Resim'),
        ),
        migrations.AlterField(
            model_name='main',
            name='accordion_interior_image',
            field=models.ImageField(blank=True, null=True, upload_to='main/', verbose_name='Interior Design Resim'),
        ),
        migrations.AlterField(
            model_name='main',
            name='accordion_landscape_image',
            field=models.ImageField(blank=True, null=True, upload_to='main/', verbose_name='Landscape Design Resim'),
        ),
        migrations.AlterField(
            model_name='main',
            name='hero_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='main/', verbose_name='Hero Arkaplan Resmi'),
        ),
        migrations.AlterField(
            model_name='main',
            name='sec1_image',
            field=models.ImageField(blank=True, null=True, upload_to='main/', verbose_name='Bölüm 1 Resim'),
        ),
        migrations.AlterField(
            model_name='main',
            name='sec2_image',
            field=models.ImageField(blank=True, null=True, upload_to='main/', verbose_name='Bölüm 2 Resim'),
        ),
    ]
