# Generated by Django 4.2.2 on 2025-03-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_main_accordion_architecture_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='hero_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Hero Video URL'),
        ),
    ]
