# Generated by Django 4.2.2 on 2025-03-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_main_hero_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Mesaj', 'verbose_name_plural': 'Mesajlar (0)'},
        ),
        migrations.AddField(
            model_name='about',
            name='values_section',
            field=models.TextField(blank=True, verbose_name='Değerler İçerik'),
        ),
        migrations.AddField(
            model_name='about',
            name='values_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Değerler Başlığı'),
        ),
        migrations.AddField(
            model_name='about',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
    ]
