# Generated by Django 4.2.2 on 2025-03-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_message_options_about_values_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='video_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Video Resmi'),
        ),
    ]
